name: SPockeR
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - pandas
  - biopython
  - pdb-tools
  - pdbfixer
  - pdb2pqr
  - apbs
  - pip
  - pip:
      - mrcfile
      - volgrids==1.0.0
      - rnapolis
